### ISSUE TITLE
Use a external application which would use the data from HPCC 

### ISSUE THREAD

**Issue by vivekaxl** [vivekaxl/HPCC-python-fuse#12]

**Comment by vivekaxl** [comment]
[Meld](http://meldmerge.org/) is a visual diff tool which can be used to display file content. The advantage of this application is that it does not read the whole file but rather reads sequentially.

**Comment by vivekaxl** [comment]
Though  I am able to view the content of the file using command line tools, the GUI tools hang as soon as it reaches the EOF. This is probably because the trailing '\n' is not added to the string.

**Comment by dcamper** [comment]
While it may not look pretty, what would happen if you appended '\n' to end of every WUResult call?  Not every record would have a trailing linefeed, but the last one would and that may be the important one.  The interim linefeeds should be ignored as well.

**Comment by vivekaxl** [comment]
I have written a regression program, which accepts 1000 records at a time and then build a partial model. This process continues till the end of the program after which a model is tested using testing data.
